// ──────────────────────────────────────────
// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Generated by dev-tools icon export
// Total: 6 icons across 1 batches
// ──────────────────────────────────────────

export interface IconEntry {
  key: string;
  prompt: string;
  file: string;
}

export interface IconBatch {
  batchId: string;
  createdAt: string;
  icons: IconEntry[];
}

export const ICON_BATCHES: IconBatch[] = [
  // Batch 3590A9A9 — 2026-02-25T15:58:22.154490+00:00 — 6 icons
  {
    batchId: '3590a9a9-bcf2-44b0-93c9-bd668c67dffe',
    createdAt: '2026-02-25T15:58:22.154490+00:00',
    icons: [
    { key: 'minimalist_monochrome_post_apocalyptic_emblem_flat_vector_high_contrast_symmetrical_single_central_symbol_isolated_icon_transparent_edges_solid_background_color_1e1e1e_uniform_icon_scale_consistent_sizing_centered_composition_clean_negative_space_no_sacred_geometry_no_mandala_no_decorative_circles_no_runes_no_glyphs_no_glow_no_gradients_no_shadows_no_background_patterns_crossed_rifle', prompt: 'minimalist monochrome post-apocalyptic emblem, flat vector, high contrast, symmetrical, single central symbol, isolated icon, transparent edges, solid background color #1e1e1e, uniform icon scale, consistent sizing, centered composition, clean negative space, no sacred geometry, no mandala, no decorative circles, no runes, no glyphs, no glow, no gradients, no shadows, no background patterns crossed rifle', file: './3590a9a9-bcf2-44b0-93c9-bd668c67dffe/000.png' },
    { key: 'minimalist_monochrome_post_apocalyptic_emblem_flat_vector_high_contrast_symmetrical_single_central_symbol_isolated_icon_transparent_edges_solid_background_color_1e1e1e_uniform_icon_scale_consistent_sizing_centered_composition_clean_negative_space_no_sacred_geometry_no_mandala_no_decorative_circles_no_runes_no_glyphs_no_glow_no_gradients_no_shadows_no_background_patterns_watchtower_shield', prompt: 'minimalist monochrome post-apocalyptic emblem, flat vector, high contrast, symmetrical, single central symbol, isolated icon, transparent edges, solid background color #1e1e1e, uniform icon scale, consistent sizing, centered composition, clean negative space, no sacred geometry, no mandala, no decorative circles, no runes, no glyphs, no glow, no gradients, no shadows, no background patterns watchtower shield', file: './3590a9a9-bcf2-44b0-93c9-bd668c67dffe/001.png' },
    { key: 'minimalist_monochrome_post_apocalyptic_emblem_flat_vector_high_contrast_symmetrical_single_central_symbol_isolated_icon_transparent_edges_solid_background_color_1e1e1e_uniform_icon_scale_consistent_sizing_centered_composition_clean_negative_space_no_sacred_geometry_no_mandala_no_decorative_circles_no_runes_no_glyphs_no_glow_no_gradients_no_shadows_no_background_patterns_scrap_spear', prompt: 'minimalist monochrome post-apocalyptic emblem, flat vector, high contrast, symmetrical, single central symbol, isolated icon, transparent edges, solid background color #1e1e1e, uniform icon scale, consistent sizing, centered composition, clean negative space, no sacred geometry, no mandala, no decorative circles, no runes, no glyphs, no glow, no gradients, no shadows, no background patterns scrap spear', file: './3590a9a9-bcf2-44b0-93c9-bd668c67dffe/002.png' },
    { key: 'minimalist_monochrome_post_apocalyptic_emblem_flat_vector_high_contrast_symmetrical_single_central_symbol_isolated_icon_transparent_edges_solid_background_color_1e1e1e_uniform_icon_scale_consistent_sizing_centered_composition_clean_negative_space_no_sacred_geometry_no_mandala_no_decorative_circles_no_runes_no_glyphs_no_glow_no_gradients_no_shadows_no_background_patterns_cracked_coin', prompt: 'minimalist monochrome post-apocalyptic emblem, flat vector, high contrast, symmetrical, single central symbol, isolated icon, transparent edges, solid background color #1e1e1e, uniform icon scale, consistent sizing, centered composition, clean negative space, no sacred geometry, no mandala, no decorative circles, no runes, no glyphs, no glow, no gradients, no shadows, no background patterns cracked coin', file: './3590a9a9-bcf2-44b0-93c9-bd668c67dffe/003.png' },
    { key: 'minimalist_monochrome_post_apocalyptic_emblem_flat_vector_high_contrast_symmetrical_single_central_symbol_isolated_icon_transparent_edges_solid_background_color_1e1e1e_uniform_icon_scale_consistent_sizing_centered_composition_clean_negative_space_no_sacred_geometry_no_mandala_no_decorative_circles_no_runes_no_glyphs_no_glow_no_gradients_no_shadows_no_background_patterns_scope_skull', prompt: 'minimalist monochrome post-apocalyptic emblem, flat vector, high contrast, symmetrical, single central symbol, isolated icon, transparent edges, solid background color #1e1e1e, uniform icon scale, consistent sizing, centered composition, clean negative space, no sacred geometry, no mandala, no decorative circles, no runes, no glyphs, no glow, no gradients, no shadows, no background patterns scope skull', file: './3590a9a9-bcf2-44b0-93c9-bd668c67dffe/004.png' },
    { key: 'minimalist_monochrome_post_apocalyptic_emblem_flat_vector_high_contrast_symmetrical_single_central_symbol_isolated_icon_transparent_edges_solid_background_color_1e1e1e_uniform_icon_scale_consistent_sizing_centered_composition_clean_negative_space_no_sacred_geometry_no_mandala_no_decorative_circles_no_runes_no_glyphs_no_glow_no_gradients_no_shadows_no_background_patterns_armor_cracked_mask', prompt: 'minimalist monochrome post-apocalyptic emblem, flat vector, high contrast, symmetrical, single central symbol, isolated icon, transparent edges, solid background color #1e1e1e, uniform icon scale, consistent sizing, centered composition, clean negative space, no sacred geometry, no mandala, no decorative circles, no runes, no glyphs, no glow, no gradients, no shadows, no background patterns armor cracked mask', file: './3590a9a9-bcf2-44b0-93c9-bd668c67dffe/005.png' }
    ],
  }
];

/** Flat map of all icons by key for quick lookup. */
export const ICONS: Record<string, IconEntry> = Object.fromEntries(
  ICON_BATCHES.flatMap(b => b.icons).map(i => [i.key, i])
);
