export const SUPPORTED_EFFECT_TARGETS = [
  'strength',
  'agility',
  'intelligence',
  'wisdom',
  'endurance',
  'charisma',
  'maxHp',
  'hp',
  'maxAp',
  'ap',
  'maxMp',
  'mp',
  'evasion',
  'defense',
  'critChance',
  'resistance',
  'socialBonus',
  'damage',
  'meleeDamage',
  'rangedAccuracy',
  'healingPower',
  'travelFuelCost',
  'travelTime',
  'ambushChance',
  'encounterChance',
  'poiRevealChance',
  'salvageYield',
  'repairCost',
  'craftingYield',
  'inventoryCapacity',
  'spoilageRate',
  'moraleLoss',
  'moraleRecovery',
  'moraleFloor',
  'trustGain',
  'trustDecay',
  'conflictChance',
  'traderPriceMultiplier',
  'negotiationSuccess',
  'peacefulResolutionChance',
  'heatGenerated',
  'resourceConsumption',
  'xpGain',
  'lootMultiplier',
  'breakdownChance',
  'mapDiscoveryRadius',
  'hazardDamage',
  'criticalFailureChance',
  'criticalFailureIgnoreChance',
  'doubleLootChance',
  'diseaseChance',
  'radiationPenalty',
  'stealthChance',
  'campSafety',
  'damageTakenMultiplier',
  'damageDealtMultiplier',
  'healingReceivedMultiplier',
  'statusResistance',
  'statusDurationMultiplier',
  'armorPenetration',
  'actionLock',
  'cannotMove',
  'cannotAttack',
  'cannotCast',
  'cannotDefend',
  'food',
  'water',
  'fuel',
  'parts',
  'armor',
  'crit_rate',
  'protection',
  'stealth',
  'fire_damage',
  'poison_damage',
  'physical_damage',
] as const;

export type SupportedEffectTarget = typeof SUPPORTED_EFFECT_TARGETS[number];

export const SUPPORTED_EFFECT_TARGET_SET = new Set<string>(SUPPORTED_EFFECT_TARGETS);

export function isSupportedEffectTarget(target?: string | null): boolean {
  return !target || SUPPORTED_EFFECT_TARGET_SET.has(target);
}
